alias ls="ls --color=always"
#alias ls="lsd"
alias ll="ls -lh"
#alias ll="lsd -lh"
alias la="ls -a"
#alias la="lsd -a"
alias lla="ls -lha"
#alias lla="lsd -lha"
alias li="ls -li"
alias grep="grep --color=always"
alias sk="sudo killall -s KILL"
alias df="df -hT"
alias du="du -hc"
alias dus="du -S | sort -n"
alias free="free -m"
alias mountiso="sudo mount -o loop"
alias fmutt="fetchmail -k -m 'procmail -d %T'; mutt"
alias pspvideo="ffmpeg -f psp -r 29.97 -b 768k -s 320x240"
alias Shutdown="sudo shutdown -h"
alias Reboot="sudo reboot"
alias Suspend="sudo pm-suspend"
alias blankscreen="xset dpms force off"
alias lockscreen="xscreensaver-command -lock"
alias animated_desktop="xwinwrap -ni -argb -fs -s -st -sp -b -nf -- /usr/lib/xscreensaver/glmatrix -window-id WID"
alias desktop_movie="xwinwrap -ni -o 0.6 -fs -s -st -sp -b -nf -- /usr/bin/mplayer -wid WID -quiet"
#alias pact="sudo pacman --config /etc/pacman_testing.conf"
#alias suspendtodisk="sudo bash -c 'echo disk > /sys/power/state'"
alias Xdebug="sudo Xephyr -ac -br -noreset -screen 800x600 :2 &"
alias pac="yay"
#alias mpd_intel="/usr/bin/mpd ~/.mpd/config_intel"
alias mpd_udac="/usr/bin/mpd ~/.mpd/config_udac"
alias mpd_hdp="/usr/bin/mpd ~/.mpd/config_hdp"
alias mpd_http="/usr/bin/mpd ~/.mpd/config_http"
alias mpd_intel="/usr/bin/mpd ~/.mpd/config_intel"
#alias mpd="/usr/bin/mpd ~/.mpd/config_intel"
alias rclist="ls /var/run/daemons"
#alias Clannad="env LC_ALL=zh_CN.utf8 LIBGL_DRIVERS_PATH=/usr/lib32/xorg/modules/dri wine ~/KEY/CLANNAD_FV/clannadFV-sc.exe"
#alias Clannad="rlvm .wine/drive_c/KEY/CLANNAD_FV/ --font ~/ipag.ttf"
#alias skype="export LIBV4LCONTROL_FLAGS=3 && LD_PRELOAD=/usr/lib32/libv4l/v4l1compat.so skype"
#alias OutputHDMI="xrandr --output HDMI1 --mode 1920x1080 -r 60 && xrandr --output LVDS1 --off"
#alias OutputLaptop="xrandr --output LVDS1 --mode 1366x768 && xrandr --size 1366x768"
alias ec="emacsclient -c"
alias et="TERM=konsole-256color emacsclient -nw"
alias sc="sudo systemctl"
alias ni="nvidia-smi"
alias t="todo.sh"
alias qvod="cd ~/Downloads/PyQvod/project/src ; python ./PyQvod.py"

# vim:filetype=zsh
